# Generated by Django 5.1 on 2024-10-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_email',
            field=models.EmailField(blank=True, default='email', max_length=80, null=True),
        ),
    ]
