# Generated by Django 5.1 on 2024-09-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=60, null=True)),
                ('name', models.CharField(max_length=60)),
                ('individual_packs', models.BooleanField(default=False)),
                ('reduced_groups', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
