# Generated by Django 5.1 on 2024-09-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_services', '0002_rename_individualservices_individualservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
