# Generated by Django 5.1 on 2024-09-07 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_services', '0003_individualtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndivService',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_hours', models.IntegerField(default=0)),
                ('duration_weeks', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='individual_services.individualtype')),
            ],
        ),
        migrations.DeleteModel(
            name='IndividualService',
        ),
    ]
