# Generated by Django 5.1 on 2024-11-03 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_services', '0004_indivservice_delete_individualservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indivservice',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
