# Generated by Django 5.1 on 2024-11-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_services', '0008_alter_indivservice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtype',
            name='friendly_name',
            field=models.CharField(default=models.CharField(max_length=254), max_length=254),
        ),
    ]
